repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format .
        types: [python]
        language: system
      - id: ty
        name: ty check
        entry: ty check .
        language: system
        pass_filenames: false
        always_run: true
