[build-system]
requires = ["uv_build>=0.11.20,<0.12.0"]
build-backend = "uv_build"


[project]
name = "engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lomi", email = "lomir@.com" }
]
requires-python = ">=3.14"
dependencies = [
    "holiday-data",
    "load-data",
    "torch>=2.12.1",
    "numpy>=2.4.0",
    "pandas>=3.0",
    "loguru>=0.7.3",
    "lightgbm>=4.6.0",
    "darts[torch]>=0.46.0",
    "weather-data",
]


[tool.uv]
prerelease = "allow"

[tool.uv.sources]
holiday-data = { workspace = true }
load-data = { workspace = true }
torch = [
    { index = "pytorch-cu132" },
]
weather-data = { workspace = true }


[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true
